### ISSUE TITLE
Bitbucket Pipelines provider is missed in the providers list

### ISSUE THREAD

**Issue by okyrdan** [aws/aws-sam-cli-pipeline-init-templates#44]
Hi team,
@aahung @c2tarun @SimonCMoore

It would be nice to add Bitbucket Pipelines as a CI/CD provider to AWS SAM Pipelines. More and more users request support for this feature.

Bitbucket Pipelines is an integrated CI/CD service built into Bitbucket. It allows you to automatically build, test, and even deploy your code based on a configuration file in your repository. Bitbucket Pipelines is one of the most used CI/CD services.

A pipeline is defined using a YAML file called bitbucket-pipelines.yml, which is located at the root of a repository. For more information on configuring a YAML file, refer to Configure bitbucket-pipelines.yml. The bitbucket-pipelines.yml file defines a Pipelines builds configuration.

An integration with AWS SAM is provided by Bitbucket Pipe: atlassian/aws-sam-deploy pipe.

The next PR will solve the issue provider **Add provider Bitbucket Pipelines** #43 

Best regards,
Oleksandr Kyrdan

**Comment by SimonCMoore** [comment]
Thanks Oleksandr we really appreciate contributions like this, I have asked the team to review.

**Comment by SimonCMoore** [comment]
Bitbucket Pipelines added as a CI/CD provider to AWS SAM Pipelines. Thanks for your help with this @okyrdan

**Comment by okyrdan** [comment]
@SimonCMoore @c2tarun @aahung Good news! Thank you!
