### ISSUE TITLE
separate AWS Accounts for each stage requires separate IAM user & access/secret keys

### ISSUE THREAD

**Issue by russellballestrini** [aws/aws-sam-cli-pipeline-init-templates#55]
`sam pipeline init --bootstrap`

Only the first stage is creating the PipelineUser IAM User and Access/Secret keys, the 2nd stage of the SAM Pipeline is skipping the user creation which is also an error.

**Comment by xazhao** [comment]
Hello! Thanks for posting the issue. I'm trying to figure out your use case. Are you trying to use the init template with 2 separate accounts or just want `bootstrap` to create separate IAM Users for each account? 

Our init templates currently don't support 2 separate AWS accounts so you might need to write your own template. If you just wish to bootstrap 2 IAM Users under separate accounts, you could delete `.aws-sam/pipeline/pipelineconfig.toml` then re-run `sam pipeline bootstrap`. That can create a new IAM user under a different account.

For your PR, deleting `_load_saved_pipeline_user_arn()` will allow creating different IAM Users for the same account, so it might not be the way we want to implement.

Let me know if you have any questions.

**Comment by russellballestrini** [comment]
I am trying to use `sam pipeline init --bootstrap` with two separate AWS accounts.

When I do this, the IAM user & keys are only created for the first stage of the SAM pipeline.

This is correct for the case when both stages use the same AWS account but incorrect when creating a real pipeline with separate AWS accounts.

The existing cookiecutter github actions yaml works with two AWS accounts with minimal modifications (using the appropriate access/secret environment vars for each tasks).

Thank you for the quick response.

**Comment by xazhao** [comment]
Hello!

Thanks for bring this up. Yes the `sam pipeline` can only uses single AWS account as of now. I will talk to the team and figure out what we would do for this. I will post updates once I have from the team.

**Comment by xazhao** [comment]
Hello @russellballestrini ! There is one thing I'd like to clarify. Using a different account for the second stage is supported but creating a second pipeline user is not supported. 

For your use case, yes you can setup the 2nd stage using a different account. Is there a specific reason that a 2nd Pipeline User is needed? Although the pipeline use is created in the first account, it doesn't affect which account will those resources will be created in.

**Comment by xazhao** [comment]
In your use case, one single Pipeline User will be created and an IAM Role will be created (assumed by the pipeline user) for each AWS accounts. In this way, the pipeline can deploy to 2 different AWS account while only one Pipeline user is needed.

Resolving the issue. Feel free to re-open it if you have more questions.
