### ISSUE TITLE
sam pipeline init for github actions fails on 1st question

### ISSUE THREAD

**Issue by tomaDev** [aws/aws-sam-cli-pipeline-init-templates#58]
sam pipeline init erroring out on 
> Error: 'Invalid question key "shared_values" referenced in default answer of question permissions_provider'

Checking for **shared_values** in the repo, indeed it's only ever referenced and isn't defined anywhere

**Comment by xazhao** [comment]
Hello! I think it's an issue of old SAM CLI version. Updating SAM CLI should fix the issue.

Ref: https://github.com/aws/aws-sam-cli-pipeline-init-templates/issues/57

I'm resolving this now. Feel free to re-open it if updating can not fix the issue.
